### ISSUE TITLE
Fcrepo - nespustí se pod Debianrm

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/osdd-docker-images#2]
Vyhazuje chyby typu
```Caused by: java.nio.file.AccessDeniedException: /usr/local/tomcat/temp/jar_cache6974567043737567883.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at sun.net.www.protocol.jar.URLJarFile$1.run(URLJarFile.java:218)
	at sun.net.www.protocol.jar.URLJarFile$1.run(URLJarFile.java:216)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.jar.URLJarFile.retrieve(URLJarFile.java:215)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:71)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 28 more
```

**Comment by leiblix** [comment]
Chyba https://github.com/docker/docker/issues/20240

Je nutné mít novější verzi aufs, než je v distribučním jádře Debianu Jessie.

```
vim /etc/apt/sources.list
deb http://mirror.one.com/debian/ jessie-backports main contrib non-free
sudo apt-get install -t jessie-backports linux-image-amd64
```
